name: kip
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - parsec
  - containers
  - mtl
  - text

executables:
  kip-lang:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
